### ISSUE TITLE
ModuleNotFoundError: No module named 'src.scalecast'

### ISSUE THREAD

**Issue by callmegar** [mikekeith52/scalecast#16]
Failing to install on intel macOS Monterey 12.6. 
Python 3.10.7
pip 22.2.2

Tried multiple versions (latest, 0.14.7, 0.13.11 all produce the same results:

Collecting scalecast
  Using cached SCALECAST-0.15.1.tar.gz (403 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/0f/m_0sfrcn7c56zl0026b1k62c0000gq/T/pip-install-k0tc2z79/scalecast_d8f7a8ae59984787adfbedc8a557540a/setup.py", line 4, in <module>
          from src.scalecast.__init__ import __version__ as version
      ModuleNotFoundError: No module named 'src.scalecast'
      [end of output]

**Comment by mikekeith52** [comment]
I tested installation for Python 3.10.7 pip 22.2.2 and could not replicate the error. I also have it installed successfully on my macOS Montery 12.6. Are you using `pip install scalecast` to install?

The only idea I have would be to clear out pip's cache and try again. Maybe this resource can help: https://www.janbasktraining.com/community/python-python/removing-pips-cache#:~:text=If%20you%20want%20to%20force,help%20you%20clear%20pip%20cache

**Comment by callmegar** [comment]
Thanks for checking, I tried the --no-cache-dir but got the same results, this is my pip location
/Library/Frameworks/Python.framework/Versions/3.10/bin/pip3
is it the same as yours, thinking it might have something to do with the paths

**Comment by callmegar** [comment]
Yes, that would be great.

**Comment by mikekeith52** [comment]
I just uploaded 0.15.2. Please try installing this version and let me know if it does or doesn't work.

**Comment by callmegar** [comment]
It worked! straight on the MacOS global install, thank you. I also tried installing 0.15.1 on a pipenv virtual environment and it also worked Ok. So it seems like it was a an issue with the paths on the MacOS

**Comment by mikekeith52** [comment]
Great news! Closing the issue.
