### ISSUE TITLE
base_estimator renamed to estimator in sklearn 1.2

### ISSUE THREAD

**Issue by adalseno** [mikekeith52/scalecast#234]
Just so you know, with version 1.2 of `sklearn` the parameter in `BaggingRegressor` has been renamed as `estimator` ([see](https://scikit-learn.org/1.2/modules/generated/sklearn.ensemble.BaggingRegressor.html)).
Thus, the file `src/scalecast/auxmodels.py` at **line 205** should be updated:
```python
final_estimator = BaggingRegressor(
->        base_estimator = MLPRegressor(
            hidden_layer_sizes=hidden_layer_sizes,
            solver=solver,
        ),
        max_samples = max_samples,
        max_features = max_features,
        n_estimators = n_estimators,
    )
```
Thank you very much for your work!

**Comment by mikekeith52** [comment]
Thank you for opening the issue! I will get this fixed soon.
