### ISSUE TITLE
Question: models save

### ISSUE THREAD

**Issue by exactstat** [mikekeith52/scalecast#26]
Hi! After all, how can I save a tuned model, feed new incoming data to it, and reuse it? Or this is out of the project stack?

**Comment by Mehul-Sanghvi** [comment]
Yeah!! I would appreciate a solution to this issue.

**Comment by mikekeith52** [comment]
Models can be pickled out and model attributes can be saved in other ways (such as referenced above: https://github.com/mikekeith52/scalecast/issues/12#issuecomment-1256282208). To access the hyperparameters of any model and forecast out with the same parameters without tuning the model again, you can use:

```python
hps = f.history[model_nickname]['HyperParams']
estimator = f.history[model_nickname]['Estimator']

f.set_estimator(estimator)
f.manual_forecast(**hps)
```

**Comment by Mehul-Sanghvi** [comment]
Thank You. @mikekeith52
