### ISSUE TITLE
Scaled Automated Forecasting with LSTM

### ISSUE THREAD

**Issue by Mehul-Sanghvi** [mikekeith52/scalecast#27]
Hello, 
I was referring to your document. I want to use the Scaled Automated Forecasting feature with LSTM too. Can you please guide me with it?

**Comment by mikekeith52** [comment]
There is currently no framework within scalecast to tune the hyperparameters of the LSTM model. You can still transform the series and use `auto_Xvar_select` to find an optimal number of lags.

**Comment by Mehul-Sanghvi** [comment]
Okay. 
Can you please share an example of auto_Xvar_select to find an optimal number of lags?

**Comment by mikekeith52** [comment]
Sure, something like this:

```python
lags = f.auto_Xvar_select(
    estimator = 'mlr', # change to any sklearn estimator
    try_trend = False,
    try_seasonalities = False,
    max_ar = 100,  # change to any integer
    monitor = 'ValidationMetricValue', # change to any metric here: https://scalecast.readthedocs.io/en/latest/Forecaster/ForecasterGlobals.html#_determine_best_by_
)
optimal_lags = max([int(x.split('AR')[-1]) for x in f.get_regressor_names()])

f.set_estimator('lstm')
f.manual_forecast(lags=optimal_lags,...)
```

**Comment by Mehul-Sanghvi** [comment]
Okay. Thank You for your help.
