### ISSUE TITLE
Forecasting with per minute time series

### ISSUE THREAD

**Issue by Mehul-Sanghvi** [mikekeith52/scalecast#28]
Hello, 

I am trying to perform time-series forecasting using scalecast. My data contains a Date column with the 10T (10 minutes) frequency. 
When I try to perform Scaled Automated Forecasting, with this frequency, it always throws me a warning because I cannot perform forecasting on the dataset. 

These are the warning currently I am facing.

**Warning 1**
WARNING:py.warnings:/usr/local/lib/python3.8/dist-packages/scalecast/Forecaster.py:2594: UserWarning: trend decomposition did not work and raised this error: freq T not understood. Please report if you think this is in error. switching to non-decomp method
  warnings.warn(

**Warning 2**
WARNING:py.warnings:/usr/local/lib/python3.8/dist-packages/scalecast/Forecaster.py:2703: UserWarning: no seasonalities are currently associated with the 10T frequency
  warnings.warn(f'no seasonalities are currently associated with the {f.freq} frequency')

I would appreciate a solution to my query.

**Comment by mikekeith52** [comment]
Hi,

This shouldn't stop you from being able to forecast with the series. Some of the functions only won't know how to apply seasonality effectively to the series since it is an uncommon frequency. Let me know if you are not getting any forecast results for the series.

**Comment by Mehul-Sanghvi** [comment]
Hi, 
Yeah !! you are correct, but the problem is that I can't generate results when I start the execution of the pipeline.fit_predit() function, it just keeps on running. My longest execution time was 1 hr 45 mins nearly.

**Comment by mikekeith52** [comment]
Depending on the length of the series and the complexity of the model being evaluated, it can take a long time to evaluate a model. Can you share your code?

**Comment by Mehul-Sanghvi** [comment]
Sorry, I can't share my code with you. But yeah I have got this thing. I reduced the length of the series and then tried. It worked perfectly. 

There is one more query I would like to ask. After using the automated scale pipeline, (pipeline.fit_predict() method) multiple models are created. I want to test those models on unseen data. Can you please help me how to execute that?
