### ISSUE TITLE
Is it possible to pickle only trained model and call it back for test and/or forecast without any training process in another .py folder?

### ISSUE THREAD

**Issue by batuhansahincanel** [mikekeith52/scalecast#3]
I am trying to pickle a trained xgboost model and call it in another .py folder to only do forecast without any training process. Is it possible to do that with auto_forecast() function, if not how can I do that? (code is below)

"""### XGBoost"""

xgboost_grid = {
    'max_depth': [15],
     'tree_method': 'gpu_hist'
}
for i, f in enumerate(forecasts):
    print('Forecast', i)
    f.set_estimator('xgboost')
    f.ingest_grid(xgboost_grid)
    f.tune()
    f.auto_forecast()

**Comment by mikekeith52** [comment]
After calling `f.auto_forecast()` and before changing the estimator, the scikit-learn trained model is available in the `regr` attribute. So, you can use code like this to do what you are asking:

```python
import pickle

xgboost_grid = {
'max_depth': [15],
'tree_method': 'gpu_hist'
}

f.set_estimator('xgboost')
f.ingest_grid(xgboost_grid)
f.tune()
f.auto_forecast()

with open('xgboost_regr.pckl','wb') as pckl:
  pickle.dump(f.regr,pckl)
```

In a separate issue, I think you need brackets around `'gpu_hist'` in the grid. If there is an error with all hyperparam combinations during grid evaluation, the model is trained with default parameters.

**Comment by batuhansahincanel** [comment]
Thanks for the response. I tried your suggested solution but I am having error in the process call it back and use it for predictions. 

Error;
ValueError: DataFrame.dtypes for data must be int, float, bool or category.  When
categorical type is supplied, DMatrix parameter `enable_categorical` must
be set to `True`.


Code;
`with open('xgboost_regr.pckl','wb') as pckl:
  pickle.dump(f.regr,pckl)
    

filename = open("xgboost_regr.pckl", "rb")
xgb_new = pickle.load(filename)
filename.close()


pickle_pred = xgb_new.predict(X_test)`


X_test concludes only date time series that i want to make forecast.

**Comment by mikekeith52** [comment]
In scalecast, the model is using a whole dataframe of predictors to make forecasts, not just the date-type column. To see the dataframe that is generated for your model, you can run:
```python
f.export_Xvars_df()
````
You will only be able to use this dataframe to predict one step into the future if you are using any AR terms. You will need to create a process that predicts future values of your AR terms to go more than one step out. But, I think the easiest way to get where you are going is to not pickle out the model and use the forecasts that scalecast produces after running `auto_forecast()` by default:
```python
f.auto_forecast()
f.export("lvl_fcsts")
```
The forecast horizon you specified in your analysis when calling `f.generate_future_dates()` will determine how many forecast steps are exported this way. The reason the package both tests and forecasts with the model in the same line of code is to simplify the dynamic process used to make predictions.

**Comment by mikekeith52** [comment]
Glad to help! Closing the issue.
