### ISSUE TITLE
Scalecast on Apple M1 

### ISSUE THREAD

**Issue by Jansza** [mikekeith52/scalecast#31]
Hello!

I've hit a bit of a wall trying to use Scalecast on Apple M1 silicon. It looks like Scalecast is requesting specifically for "tensorflow" package as a prerequisite when installing.

Would it be possible to have the requirement be either "tensorflow" or tensorflow for M1 macs named "tensorflow-macos"?

Best regards,
Jaanus

**Comment by mikekeith52** [comment]
Hi Jansza,

Yes I think it's time we take tensorflow out of the requirements and place it (as well as tensorflow-macos) into the optional add-ons. Give me a few days to make that update but expect it in `0.15.15`. Thank you for bringing this up.
