### ISSUE TITLE
Model Testing on Unseen data, when that model is trained using Automated Scale Pipeline methodology.

### ISSUE THREAD

**Issue by Mehul-Sanghvi** [mikekeith52/scalecast#32]
There is a query I would like to ask. After using the automated scale pipeline, (pipeline.fit_predict() method) multiple models are created. I want to test those models on unseen data and need to deploy them for real-time data too. Can you please help me how to execute that?

**Comment by mikekeith52** [comment]
Hi, all these modes are tested on unseen data. See the documentation for [extracting test-set results](https://scalecast.readthedocs.io/en/latest/Forecaster/Forecaster.html#src.scalecast.Forecaster.Forecaster.export) and [plotting the test set](https://scalecast.readthedocs.io/en/latest/Forecaster/Forecaster.html#src.scalecast.Forecaster.Forecaster.plot_test_set). If you have separate datasets with the data you need to test, you can still use the first link to extract your forecast results which can be compared to the data in the separated datasets. See [metrics](https://scalecast.readthedocs.io/en/latest/Forecaster/Util.html#src.scalecast.util.metrics) for some metrics that can be used to compare results.

**Comment by Mehul-Sanghvi** [comment]
Does it mean that every time I have to use the fit_predict() method to run models on unseen data?
