### ISSUE TITLE
impact of exogenous variable on forecasted values

### ISSUE THREAD

**Issue by ahmad-shahi** [mikekeith52/scalecast#37]
it is good to add such a functionality that tells for instance how much exogenous variable impacted on forecasted value. like climate changes as an exog.

**Comment by mikekeith52** [comment]
Hi, feature importance through permutation feature importance and shap are available. Summary stats are also available for some models. Here are some resources:

https://scalecast.readthedocs.io/en/latest/Forecaster/Forecaster.html#src.scalecast.Forecaster.Forecaster.save_feature_importance
https://scalecast.readthedocs.io/en/latest/Forecaster/Forecaster.html#src.scalecast.Forecaster.Forecaster.save_summary_stats
https://scalecast.readthedocs.io/en/latest/Forecaster/Forecaster.html#src.scalecast.Forecaster.Forecaster.export_feature_importance
https://scalecast.readthedocs.io/en/latest/Forecaster/Forecaster.html#src.scalecast.Forecaster.Forecaster.export_summary_stats
https://scalecast-examples.readthedocs.io/en/latest/misc/feature-selection/feature_selection.html

I'm closing the issue for now. Thanks,
