### ISSUE TITLE
Lags seems not working with tune_test_forecast in MVForecaster

### ISSUE THREAD

**Issue by Coemgenus** [mikekeith52/scalecast#38]
Hello,

Thanks for your wonderful library.

Juste a note, but it seems that in MVForecaster the function tune_test_forecast does not take into account the lags.

When I check the results, everything is similar to use manual_forecast(lags=1) 

I’ve tried to use add_ar in every single Forecaster used in MVForecaster but without success 

I’m using the last version of the library (0.17.14)

Regards,

**Comment by mikekeith52** [comment]
Hi,

So to take lags into account in `tune_test_forecast()`, you would need to add a lags key to your dictionary grid:

```python
mlr_grid = {'lags':[1,2,3,4,5]}
f.ingest_grid(mlr_grid)
f.tune()
f.auto_forecast()
```
You can see how many lags were selected by then calling
```python
f.best_params
```

This works the same way for `tune_test_forecast()`, except now the grids are stored in an external file (`MVGrids.py` by default) and you can export the lag selections for all models by calling `mvf.export('model_summaries')`.

Let me know if that doesn't answer the question.

**Comment by Coemgenus** [comment]
Oh i see that’s clear for me, sorry for wasting your time on this one ! 

Thankyou
