### ISSUE TITLE
PDEP datetime warnings.

### ISSUE THREAD

**Issue by fcekalovic** [mikekeith52/scalecast#39]
Hello Mike, there are some changes in pandas and Forecaster now raises some warnings,

https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html

Forecaster.py:1296: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  self.future_dates = pd.to_datetime(

Forecaster.py:1305: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  self.future_dates = pd.to_datetime(

**Comment by mikekeith52** [comment]
This was fixed in the distribution update committed today. Please feel free to download 0.18.4. Thanks for opening the issue!
