### ISSUE TITLE
from scalecast.Forecaster import Forecaster gives error

### ISSUE THREAD

**Issue by pmudgal-Intel** [mikekeith52/scalecast#46]
While importing scalecast "from scalecast.Forecaster import Forecaster", I get the below error.
scalecast version - 0.18.4
pandas version 2.0.1
packages/lightgbm/__init__.py:8), in 
      2 """LightGBM, Light Gradient Boosting Machine.
      3 
      4 Contributors: https://github.com/microsoft/LightGBM/graphs/contributors.
      5 """
      6 from pathlib import Path
----> 8 from .basic import Booster, Dataset, Sequence, register_logger
      9 from .callback import early_stopping, log_evaluation, print_evaluation, record_evaluation, reset_parameter
     10 from .engine import CVBooster, cv, train
...
    279 def split(self, pat=None, n=-1, expand=False):
    280     """Known inconsistencies: ``expand=True`` with unknown ``n`` will raise a ``NotImplementedError``."""
    281     return self._split("split", pat=pat, n=n, expand=expand)

AttributeError: module 'pandas.core.strings' has no attribute 'StringMethods'
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?cf84fd14-4a6d-4ff6-91da-43a82336facc) or open in a [text editor](command:workbench.action.openLargeOutput?cf84fd14-4a6d-4ff6-91da-43a82336facc). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

**Comment by pmudgal-Intel** [comment]
Tried with suggested lightgbm version, but still getting the same error.

**Comment by mikekeith52** [comment]
Can you try running `pip install --upgrade dask`?

**Comment by pmudgal-Intel** [comment]
That worked. Thanks.

**Comment by mikekeith52** [comment]
Great! Closing the issue.
