### ISSUE TITLE
Return a dataframe for the forecasted future values

### ISSUE THREAD

**Issue by Lagstill** [mikekeith52/scalecast#53]
![image](https://github.com/mikekeith52/scalecast/assets/89288089/76407f50-ef25-4e62-8112-50bc721ca6aa)
I have the future forecast and able to plot it by setting f.fututre_genrations(), but I am not able to retrieve those values as dataframe. Like none of this includes a dataframe to return the result of fufture generations "dfs=['model_summaries','lvl_fcsts','lvl_test_set_predictions']"

**Comment by Lagstill** [comment]
I resolved by save_df in plot function. But a separate export options would be nice.

**Comment by mikekeith52** [comment]
Are you suggesting the `f.export('lvl_fcsts')` is not working in your case? Can you send me the error? See the [docs](https://scalecast.readthedocs.io/en/latest/Forecaster/Forecaster.html#src.scalecast.Forecaster.Forecaster.export).

**Comment by Lagstill** [comment]
Fixed thanks.
