### ISSUE TITLE
ForecastError: Need at least 1 Xvar to forecast with the svr model.

### ISSUE THREAD

**Issue by amengjiao** [mikekeith52/scalecast#56]
Hello! 

I am running the code below from your medium article: https://towardsdatascience.com/forecast-on-3-levels-introducing-scalecast-pt-3-eb725e0be6c9

f.set_validation_length(6)
# automatically tune and forecast with a series of models
models = ('mlr','knn','svr','xgboost','gbt','elasticnet','mlp','prophet')
for m in models:
 f.set_estimator(m)
 f.tune() # by default, will pull grids from Grids.py
 f.auto_forecast()

Here is the error message I got:
ForecastError: Need at least 1 Xvar to forecast with the svr model.

Would you please help? Thank you!

**Comment by mikekeith52** [comment]
Yes, to make this one work, you need to add inputs to the model, such as series lags or seasonal terms. I usually use

`f.auto_Xvar_select(ignore_trend=True)`

To get me started. Try running that before you begin the loop. You can also see:

- [Adding series lags](https://scalecast.readthedocs.io/en/latest/Forecaster/Forecaster.html#src.scalecast.Forecaster.Forecaster.add_ar_terms)
- [Adding seasonal terms](https://scalecast.readthedocs.io/en/latest/Forecaster/Forecaster.html#src.scalecast.Forecaster.Forecaster.add_seasonal_regressors)
