### ISSUE TITLE
Forecasting using Dates but also Categorical (Exgegenuous) Features

### ISSUE THREAD

**Issue by raedbsili1991** [mikekeith52/scalecast#60]
Hello, 

Is it possible to perform prediction by taking inputs the dates but also some categorical features ? (Such as Exegenuous variables in Skforecast) ?

**Comment by mikekeith52** [comment]
Yes, you can add any exogenous regressors you want using `f.ingest_Xvars_df()`. See the [docs](https://scalecast.readthedocs.io/en/latest/Forecaster/Forecaster.html#src.scalecast.Forecaster.Forecaster.ingest_Xvars_df). There are other ways to add exogenous variables and to use direct forecasting if you don't know the future values, but this is the primary method.
