### ISSUE TITLE
additional regressor for prophet does not work 

### ISSUE THREAD

**Issue by sykrn** [mikekeith52/scalecast#63]
The problem why additional regressor for prophet does not work due to these lines.
the `regr` object overrides the previous `model` with additional regressors.

        model = Prophet(**kwargs)
        for x in Xvars:
            model.add_regressor(x)
        regr = Prophet(**kwargs)
        regr.fit(X)
        fcst = regr.predict(p)

https://github.com/mikekeith52/scalecast/blob/1a8301784fcd60b07bb963896c83ca1ccdf244cd/src/scalecast/Forecaster.py#L561C1-L566C31

**Comment by mikekeith52** [comment]
Oof. That's a pretty egregious mistake on my part. I will have that fixed very soon, in the next release.

**Comment by sykrn** [comment]
Thanks @mikekeith52, waiting for the next release. :)

**Comment by mikekeith52** [comment]
Can I get you to review pull request #64? I confirmed that the code works but want to get your eyes on it to make sure there are no additional problems than what I was able to change.

**Comment by mikekeith52** [comment]
You should be able to upgrade to 0.18.11: `pip install --upgrade scalecast`

**Comment by mikekeith52** [comment]
Can we close this issue?
