### ISSUE TITLE
 [Errno 2] No such file or directory when install

### ISSUE THREAD

**Issue by chpiero** [mikekeith52/scalecast#9]
when i try to install scalecast as ' pip install scalecast ', 'have this error:

`FileNotFoundError: [Errno 2] No such file or directory: './docs/source/Forecaster/examples/eCommerce.ipynb'`

my system is a OSX 12.5 M1

**Comment by mikekeith52** [comment]
That is an odd error. Looks like it is trying to find a document that existed in an older distribution but that is not there with newer releases. I'm sure somebody would know what is going on here, but it's not something I've ever run into. I can suggest trying simple fixes:

`pip install --upgrade scalecast`

If that doesn't work:

`pip uninstall scalecast`
`pip install scalecast==0.13.11`

If neither of those solutions works, please let me know and I'll look into it further.
